randomTitle();
function randomTitle() {
    var titles = [
        "Welcome Home!", 
        "It's been a long day...", 
        "That looks like the battlepass", 
        "rcd1.github.io", 
        "ᓚᘏᗢ", 
        "(￣y▽￣)╭ Ohohoho.....",
        "(⓿_⓿)",
        "Don't forget your breakfast!",
        "Is your refrigerator running?",
        "Care for an egg in these trying times?",
        "Surely you can't be serious",
        "Sonic 3 is a good christmas movie",
        "Keep your feet on the ground!",
        "Well, it's just a theory anyways",
        "Happy Birthday Geralt!",
        "Who decided that?",
        "Ice Bear is learning javascript",
        "Wanna break from the ads?",
        "I've been waiting for the longest time",
        "Put these foolish ambitions to rest",
        "CURSE YOU BAYLE",
        "You won!",
        "You lost ;-;",
        "You tied? How?",
        "They said I would never teach a llama to drive",
        "Could we hold hands on the jouch?",
        "Your hair is looking great today",
        "Nice glasses!",
        "This is good news",
        "We can live for 30 years",
        "I guess they never miss, huh?",
        "Flint and Steel!",
        "Chicken Jockey!",
        "L-l-l-lava ch-ch-ch-chicken",
        "Then perish",
        "WITH A HAIL OF HARPOONS",
        "Home of the Goodburger",
        "1 second cooldown BY THE WAY",
        "Calc is short for calculator btw",
        "Happy Birthday!",
        "First time?",
        "I have been called, I must answer.",
        "iiiiiiiiiit's SPIDER TIME",
        "LEEEEEEEEEEGENDARYYYYYYYYY",
        "THE MOON HAUNTS YOU",
        "YOUR POWERS ARE MINE",
        "PUUUURRRREEEE CHAOOOOOOOS",
        "Thank you Baptiste, Oh! You're welcome!",
        "Ahh heck yeah jigsaw you the GOAT",
        "You're one in a krillion",
        "You're telling me a shrimp fried this rice?",
        "Chef's kiss? D-do they really?",
        "Apartment complex? I find it quite simply actually.",
        "The bird flu? Uh, yeah, they kinda do that.",
        "Please excuse the mess",
        "Maybe my bees will help!",
        "You are being saved, please do not resist.",
        "Take me to snurch 🐌",
        "Have you ever watch a snail eat?",
        "All my fellas!",
        "What's new Scooby-Doo?",
        "Who're you gonna call?",
        "Gotta catch 'em all!",
        "Source? Trust me",
        "It was revealed to me in a dream.",
        "Is that a Jojo reference?",
        "Bird up!",
        "Viktor Nation, how we feeling?",
        "Use your strand Guardian!",
        "Take a Map",
        "Hello? Hello Hello?",
        "I ALWAYS COME BACK",
        "You're my friend now",
        "But nobody came.",
        "Just ony more sweet treat",
        "Fired up like a volcano!",
        "Son can you play me a melody?",
        "Have you heard the Tragedy of Darth Plagueis the Wise?",
        "My roflcopter go swaws swaws swaws swaws",
        "You just got coconut-malled!",
        "I drank shampoo",
        "Bold and Brash?",
        "You just gotta push your temper!",
        "My name is edwin, I made the mimic",
        "I am now become sleepy, honker of shoos",
        "It's 5 o' clock somewhere",
        "No running in the halls",
        "I was ready for a battle of wits, but it appears you're unarmed",
        "Bart, I don't mean to alarm you",
        "GOTTA SWEEP SWEEP SWEEP",
        "Is that that Bite of 87??",
        "DO NOT THE CAT",
        "Together we will devour the very gods",
        "Hive Approaching! Bring a Sword",
        "Bank and you'll summon a Primevil!",
        "Guardian, we stand on the precipice of a war with the cabal",
        "You can play as Luigi now"
    ];
    document.title = titles[Math.floor(Math.random() * titles.length)]

}